### ISSUE TITLE
Make crafting recipe/s

### ISSUE THREAD

**Issue by Xander-Fury** [drazisil/BiomeCompass#6]
early late game, one version that locates biomes, one that locates and tp's player to biome

**Comment by drazisil** [comment]
So you are wanting 2 items?

I'm thinking tghe crafting recipe should use maps. Wonder if I can check a map to see if it's fully filled out.

**Comment by drazisil** [comment]
Recipe exists for base model. Will need to add more to support #7

**Comment by drazisil** [comment]
Recipes are mostly done. Need to come up with a good one for the tp model. @Xander-Fury wants it expensive, I want it it single-use.

**Comment by Xander-Fury** [comment]
Submitted potential recipes for single use, and multi-use teleport compass versions, and additional crafting ingredients.
