### ISSUE TITLE
multiple versions increasing in cost to craft, allowing expanded search radius?  

### ISSUE THREAD

**Issue by Xander-Fury** [drazisil/BiomeCompass#7]
tiered crafting structure, for increased capabilities in late game?

**Comment by drazisil** [comment]
This is tied to #6 , but slightly different.

**Comment by drazisil** [comment]
Search radius is tied to configure. We could make different versions, but I think I want to keep it in configs so server admins retain control over the stability of their server. Gonna close this for now
