### ISSUE TITLE
Edit item to use custom texture

### ISSUE THREAD

**Issue by drazisil** [drazisil/BiomeCompass#8]
Would like custom texture so you can tell apart from vanilla compass

Right now the only way to tell is it's not animated.

**Comment by drazisil** [comment]
I think @Xander-Fury should take this one

**Comment by Xander-Fury** [comment]
is working on it

**Comment by drazisil** [comment]
This shold have been closed as of commit 76419420a9784b6ab4c0bf8068dc060758d3c3e2
